.github/workflows/quality_control.yml

- Set up quality control workflow
- Runs pytest on all .py files
- Runs pylint (set fail threshold to a score of 8).

Created quality_control.yml github workflow

---

README.md

- Architecture and Database Design
- Folders
- Getting Setup
- Authors
- Version History

Will Banks - Created folder descriptions for Readme and section headings

---

README.md

Added a small description for the ERD diagram. Let me know if any changes are needed/more details need could be added
closes #27

Add description to ERD on readme

---

.gitignore
database/data.tf
database/main.tf
database/variables.tf

- Created security group to allow RDS to listen to connections from postgres default port
- Created RDS to store real-time earthquake data

Wb rds config

---

database/schema.sql

SQL file that creates the tables for earthquakes, alerts, networks, types, status and mag_types. 
Also has seeding for typical values for the alerts, networks, types, status, and mag_types tables.

Database schema

---

.gitignore
pipeline/extract.py
pipeline/requirements.txt

Added the code required to run the extract process of the ETL

Extract pipeline

---

database/connect.sh
database/run_schema.sh

- Script to allow user to connect to db
- Script to allow user to run schema against db

2 shell scripts for user

---

database/schema.sql

- Schema bug fixes
- Improved readability

Wb schema patch

---

dashboard/.streamlit/config.toml
dashboard/main.py
dashboard/pages/notifications.py
dashboard/requirements.txt

Added key files to the dashboard folder - such as a pages folder that allows the dashboard to have multiple pages and a config.toml which allows for customisation.

added important files

---

weekly-report/db_connect.py
weekly-report/main.py
weekly-report/main.tf
weekly-report/requirements.txt
weekly-report/variables.tf
weekly-report/visuals.py

- Created terraform file, and template for eventbridge scheduler to trigger at 9am every Friday.
- Created script to make connection db and get cursor

weekly report workflow file setup

---

api/api.py
api/requirements.txt
api/test_api.py

added initial files to the api folder, including a main and test program. Main program includes an endpoint index to test that the api can be hosted locally. Requirements have also been added to the requirements.txt file.

add api setup files

---

weekly-report/main.tf
weekly-report/variables.tf

- Created Bucket to store weekly reports
- Created Eventbridge scheduler to target lambda function at 9am every friday
- Created Lambda function to generate weekly PDF reporting

Wb weekly report

---

api/api.py
api/requirements.txt
api/test_api.py

added functionality to the api program so that it connects to the earthquake RDS and retrieves all earthquake data.
Tests have been included for the default index and the earthquakes index.

add database connection to api 

---

pipeline/conftest.py
pipeline/requirements.txt
pipeline/test_transform.py
pipeline/transform.py

Adding updated transform script with bug fixes

Test transform

---

pipeline/main.tf
pipeline/variables.tf

- Created pipeline scheduler, lamdba and iam role
- Given permissions to access RDS and commit to an SNS topic

Wb terraform pipeline

---

pipeline/handler.py

Created a lambda handler function

Lambda handler

---

api/api.py
api/requirements.txt
api/test_api.py

Added an option to filter earthquake data from one of seven continents:
North America
South America
Asia
Africa
Oceania
Europe
Antarctica

Api continent filter

---

api/api.py
api/test_api.py

Current api is able to get a country's name through the earthquakes endpoint and return a list of events pertaining to that country
Next steps involve refactoring the code, which includes remove/reformatting dry code

Api country filter

---

dashboard/.streamlit/config.toml
dashboard/charts.py
dashboard/main.py
dashboard/requirements.txt

Main page of dashboard done, contains various visualisations using the data from the database.

Dashboard main

---

api/api.py
api/conftest.py
api/test_api.py

Refactored code to have a location function that then calls the country or continent filter based on the inputs given.
This makes the function getting all the earthquake data easier to read and understand.

Api location filters

---

dashboard/.streamlit/config.toml
dashboard/main.py
dashboard/pages/notifications.py

Added emojis and page names, changed the background colours to make the dashboard more visually appealing.

Customised dashboard

---

api/README.md

The README file in the api directory should be clear enough for new users/collaborators to learn the functionality of this program.

Api readme

---

api/Dockerfile

This PR aims to provide a Dockerfile that will allow the api to run on port 5000.

Api dockerise

---

dashboard/pages/weekly_report.py

Added a page that has links to download weekly pdf reports on earthquakes. Currently works

Dashboard weekly report

---

api/data.tf
api/main.tf
api/variables.tf

- Created Terraform Script for API Service
- Tested on Service runs on cloud - all clear

moved api service to cloud

---

dashboard/Dockerfile
dashboard/charts.py
dashboard/main.py
dashboard/pages/weekly_report.py
dashboard/requirements.txt

Added improvements to the dashboard such as earthquake information. Also added a dockerfile in order to build an image to upload to AWS.

Dashboard improvement and dockerise

---

.gitignore
dashboard/README.md
pipeline/README.md

Adjusted pipeline readme to match formatting in dashboard readma

Pipeline readme

---

api/Dockerfile
api/api.py
api/push_api_to_cloud.sh

This PR aims to add more logging for the api, so that developers can check that the api is working as intended more easily.

Api logging

---

README.md
api/README.md
dashboard/README.md
database/README.md

Database readme

---

weekly-report/visuals.py

- Took scaling values off US state map
- Made cosmetic tweaks to pie chart

cosmetic tweaks

---

weekly-report/README.md
weekly-report/main.py
weekly-report/test_main.py
weekly-report/visuals.py

- Added tests to main.py script in weekly reporting

added tests to reporting main script

---

api/api.py
api/conftest.py

This PR aims to fix the last few pylint issues in the api.py file

Api linting

---

README.md

added acknowledgements to the main readme

added acknowledgments
